<?
$PERM["error.log.old"]["10"]="D";
$PERM["error.log.old"]["12"]="D";
$PERM["error.log.old"]["6"]="D";
$PERM["error.log.old"]["8"]="D";
$PERM["error.log.old"]["11"]="D";
$PERM["error.log.old"]["9"]="D";
$PERM["error.log.old"]["2"]="D";
$PERM["error.log"]["10"]="D";
$PERM["error.log"]["12"]="D";
$PERM["error.log"]["6"]="D";
$PERM["error.log"]["8"]="D";
$PERM["error.log"]["11"]="D";
$PERM["error.log"]["9"]="D";
$PERM["error.log"]["2"]="D";
$PERM["sale"]["10"]="R";
$PERM["sale"]["12"]="R";
$PERM["sale"]["6"]="R";
$PERM["sale"]["8"]="R";
$PERM["sale"]["11"]="R";
$PERM["sale"]["9"]="R";
$PERM["sale"]["2"]="R";
$PERM["sale"]["*"]="R";
$PERM["price"]["2"]="R";
$PERM["/"]["*"]="R";
?>