<?
$aMenuLinks = Array(
    Array(
        "Массажное оборудование", 
        "/massazhnoe-oborudovanie/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Здоровье и красота", 
        "/zdorovie-krasota/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Фитнес", 
        "/fitnes/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Терапия", 
        "/terapiya/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Дом и Дача", 
        "/dom-dacha/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Распродажа", 
        "/sale/", 
        Array(), 
        Array(), 
        "" 
    ),	
    Array(
        "О нас", 
        "/about/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Где купить", 
        "/shou-rum/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Контакты", 
        "/contacts/", 
        Array(), 
        Array(), 
        "" 
    ),	
    Array(
        "Оплата", 
        "/payment/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Доставка и сборка", 
        "/delivery/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Гарантия", 
        "/guarantee/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Обмен и возврат товара", 
        "/obmen-vozvrat-tovara/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "TRADE IN", 
        "/trade-in/", 
        Array(), 
        Array(), 
        "" 
    ),	
    Array(
        "Производители", 
        "/brands/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Статьи", 
        "/articles/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Новости", 
        "/news/", 
        Array(), 
        Array(), 
        "" 
    ),	
    Array(
        "Прайс", 
        "/price/", 
        Array(), 
        Array(), 
        "" 
    ),	
);
?>