<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "Массажеры, массажные, кресла, офисные, качалки, аппараты, терапия, фитнес, тренажеры, интернет-магазин, купить, известный, производитель, товары, продукция, бренд, фирменный, качество");
$APPLICATION->SetTitle("Производители");
$APPLICATION->SetPageProperty('title', 'Производители | Интернет-магазин «RELAXA STAR»');
$APPLICATION->SetPageProperty("description", "Купить товары известных производителей в интернет-магазине «RELAXA STAR». Большая гарантия, бесплатная доставка, акции, скидки. ☎ Телефон: 8 (800) 333 00 51 ← Звоните прямо сейчас!");

$arDirProperties = Array(
   "description" => "Все производители",
   "keywords" => "Все производители"
);

?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"brands", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "N",
		"COLOR_NEW" => "3E74E6",
		"COLOR_OLD" => "C0C0C0",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_AS_RATING" => "rating",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"HIDE_MEASURES" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "17",
		"IBLOCK_TYPE" => "info",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "OFFERS",
			1 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "500",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "round",
		"PAGER_TITLE" => "Производители",
		"PERIOD_NEW_TAGS" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PRODUCT_CONVERT_CURRENCY" => "Y",
		"PRODUCT_CURRENCY_ID" => "RUB",
		"PRODUCT_FILTER_NAME" => "arrFilter",
		"PRODUCT_IBLOCK_ID" => "1",
		"PRODUCT_IBLOCK_TYPE" => "catalog",
		"PRODUCT_PRICE_CODE" => array(
			0 => "Розничная",
		),
		"PRODUCT_PROPERTY_CODE" => array(
			0 => "ATT_BRAND",
			1 => "CML2_ARTICLE",
			2 => "TYPE",
			3 => "OFFERS",
			4 => "POWER",
			5 => "SIMILAR_PRODUCT",
			6 => "RELATED_PRODUCT",
			7 => "BLOG_POST_ID",
			8 => "BLOG_COMMENTS_CNT",
			9 => "SKU_COLOR",
			10 => "USER_ID",
			11 => "COLOR",
			12 => "ZOOM2",
			13 => "BATTERY_LIFE",
			14 => "SWITCH",
			15 => "GRAF_PROC",
			16 => "LENGTH_OF_CORD",
			17 => "DISPLAY",
			18 => "LOADING_LAUNDRY",
			19 => "FULL_HD_VIDEO_RECORD",
			20 => "INTERFACE",
			21 => "COMPRESSORS",
			22 => "Number_of_Outlets",
			23 => "MAX_RESOLUTION_VIDEO",
			24 => "MAX_BUS_FREQUENCY",
			25 => "MAX_RESOLUTION",
			26 => "FREEZER",
			27 => "POWER_SUB",
			28 => "HARD_DRIVE_SPACE",
			29 => "MEMORY",
			30 => "OS",
			31 => "ZOOM",
			32 => "PAPER_FEED",
			33 => "SUPPORTED_STANDARTS",
			34 => "VIDEO_FORMAT",
			35 => "SUPPORT_2SIM",
			36 => "MP3",
			37 => "ETHERNET_PORTS",
			38 => "MATRIX",
			39 => "CAMERA",
			40 => "PHOTOSENSITIVITY",
			41 => "DEFROST",
			42 => "SPEED_WIFI",
			43 => "SPIN_SPEED",
			44 => "PRINT_SPEED",
			45 => "SOCKET",
			46 => "IMAGE_STABILIZER",
			47 => "GSM",
			48 => "SIM",
			49 => "MEMORY_CARD",
			50 => "TYPE_BODY",
			51 => "TYPE_MOUSE",
			52 => "TYPE_PRINT",
			53 => "CONNECTION",
			54 => "TYPE_OF_CONTROL",
			55 => "TYPE_DISPLAY",
			56 => "TYPE2",
			57 => "REFRESH_RATE",
			58 => "RANGE",
			59 => "AMOUNT_MEMORY",
			60 => "MEMORY_CAPACITY",
			61 => "VIDEO_BRAND",
			62 => "DIAGONAL",
			63 => "RESOLUTION",
			64 => "TOUCH",
			65 => "CORES",
			66 => "LINE_PROC",
			67 => "PROCESSOR",
			68 => "CLOCK_SPEED",
			69 => "TYPE_PROCESSOR",
			70 => "PROCESSOR_SPEED",
			71 => "HARD_DRIVE",
			72 => "HARD_DRIVE_TYPE",
			73 => "Number_of_memory_slots",
			74 => "MAXIMUM_MEMORY_FREQUENCY",
			75 => "TYPE_MEMORY",
			76 => "BLUETOOTH",
			77 => "FM",
			78 => "GPS",
			79 => "HDMI",
			80 => "SMART_TV",
			81 => "USB",
			82 => "WIFI",
			83 => "FLASH",
			84 => "ROTARY_DISPLAY",
			85 => "SUPPORT_3D",
			86 => "SUPPORT_3G",
			87 => "WITH_COOLER",
			88 => "FINGERPRINT",
			89 => "COLLECTION",
			90 => "TOTAL_OUTPUT_POWER",
			91 => "HTML",
			92 => "VID_ZASTECHKI",
			93 => "VID_SUMKI",
			94 => "VIDEO",
			95 => "PROFILE",
			96 => "VYSOTA_RUCHEK",
			97 => "GAS_CONTROL",
			98 => "WARRANTY",
			99 => "GRILL",
			100 => "MORE_PROPERTIES",
			101 => "GENRE",
			102 => "OTSEKOV",
			103 => "CONVECTION",
			104 => "INTAKE_POWER",
			105 => "NAZNAZHENIE",
			106 => "BULK",
			107 => "PODKLADKA",
			108 => "SHOW_MENU",
			109 => "SURFACE_COATING",
			110 => "brand_tyres",
			111 => "SEASON",
			112 => "SEASONOST",
			113 => "DUST_COLLECTION",
			114 => "REF",
			115 => "COUNTRY_BRAND",
			116 => "DRYING",
			117 => "REMOVABLE_TOP_COVER",
			118 => "CONTROL",
			119 => "FINE_FILTER",
			120 => "FORM_FAKTOR",
			121 => "DELIVERY",
			122 => "VOTE_COUNT",
			123 => "MARKER_PHOTO",
			124 => "NEW",
			125 => "DELIVERY_DESC",
			126 => "SALE",
			127 => "RATING",
			128 => "PICKUP",
			129 => "VOTE_SUM",
			130 => "MARKER",
			131 => "POPULAR",
			132 => "WEIGHT",
			133 => "HEIGHT",
			134 => "DEPTH",
			135 => "WIDTH",
			136 => "",
		),
		"SEF_FOLDER" => "/brands/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "TIMESTAMP_X",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "DESC",
		"STRICT_SECTION_CHECK" => "N",
		"TAGS_CLOUD_ELEMENTS" => "150",
		"TAGS_CLOUD_WIDTH" => "100%",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "brands",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"FILE_404" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?><?$APPLICATION->IncludeComponent("dresscode:slider", ".default", array(
	"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "Y",
		"COMPONENT_TEMPLATE" => ".default",
		"IBLOCK_ID" => "4",
		"IBLOCK_TYPE" => "content",
		"PICTURE_HEIGHT" => "202",
		"PICTURE_WIDTH" => "1476",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false,
	array(
	"ACTIVE_COMPONENT" => "N"
	)
);?>
<?php 
	$current_uri = parse_url($_SERVER['REQUEST_URI']);
	if ($current_uri['path'] == '/brands/') {
		$APPLICATION->SetTitle("Производители");
		$APPLICATION->SetPageProperty('title', 'Производители | Интернет-магазин «RELAXA STAR»');
		$APPLICATION->SetPageProperty("description", "Товары различных брендов в интернет-магазине RELAXA STAR. Предлагаем купить оборудование по выгодным ценам в Москве. Гарантия качества, широкий ассортимент, индивидуальный подход. Наш телефон: +7 (495) 789-91-74");
	}
?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>